### ISSUE TITLE
Yaml parsing fails with `symfony/yaml` 3.0.0

### ISSUE THREAD

**Issue by Ocramius** [FriendsOfPHP/security-advisories#130]
Hit it by accident, but strings such as [`versions: [>=3.0.0,<3.2.1]`](https://github.com/FriendsOfPHP/security-advisories/blob/f1ff98c2154fd33389d3f4e082f63d38d7352257/aws/aws-sdk-php/2015-08-31.yaml#L7) don't seem to be valid Yaml.

Here is an example trace of how I hit this:

```
PHP Fatal error:  Uncaught Symfony\Component\Yaml\Exception\ParseException: The reserved indicator ">" cannot start a plain scalar; you need to quote the scalar at line 7 (near "versions: [>=3.0.0,<3.2.1]"). in vendor/symfony/yaml/Inline.php:241
Stack trace:
#0 vendor/symfony/yaml/Inline.php(317): Symfony\Component\Yaml\Inline::parseScalar('[>=3.0.0,<3.2.1...', Array, Array, 8, true, Array)
#1 vendor/symfony/yaml/Inline.php(63): Symfony\Component\Yaml\Inline::parseSequence('[>=3.0.0,<3.2.1...', 8, Array)
#2 vendor/symfony/yaml/Parser.php(479): Symfony\Component\Yaml\Inline::parse('[>=3.0.0,<3.2.1...', true, false, false, Array)
```

**Comment by xabbuh** [comment]
see #131

**Comment by Ocramius** [comment]
\o/
